apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: llm-alerting
build:
  artifacts:
    - image: _REGION-docker.pkg.dev/_PROJECT_ID/k8s-asst/llm-alerting
      buildpacks:
        builder: gcr.io/buildpacks/builder:google-22
        runImage: _REGION-docker.pkg.dev/_PROJECT_ID/k8s-asst/llm-alerting-base
        dependencies:
          ignore:
            - ".gitignore"
            - "*.md"
            - "*.yaml"
            - bin/**

manifests:
  rawYaml:
    - resources/*

deploy:
  cloudrun:
    projectid: _PROJECT_ID
    region: _REGION

