apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: llm-altering
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/skaffold-buildpacks
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        # builder: paketobuildpacks/builder-jammy-base

manifests:
  rawYaml:
    - cloud-run-service.yaml
