apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: llm-alerting
  annotaions:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: "llm-alerting"
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containers:
        - name: llm-alerting
          image: asia-southeast1-docker.pkg.dev/play-dev-ops/k8s-asst/llm-alerting
          ports:
          - name: http1
            containerPort: 8000
          env:
            - name: "PROJECT_ID"
              value: "play-dev-ops"
            - name: "REGION"
              value: "asia-southeast1"
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
