apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: llm-alerting
  annotaions:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: "llm-alerting"
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containers:
        - name: llm-alerting
          image: <_REGION>-docker.pkg.dev/<_PROJECT_ID>/k8s-asst/llm-alerting
          ports:
          - name: http1
            containerPort: 8000
          env:
            - name: "PROJECT_ID"
              value: "<_PROJECT_ID>"
            - name: "REGION"
              value: "<_REGION>"
            - name: "WEBHOOK_URL"
              value: "<_WEBHOOK_URL>"
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
